services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: safe_monitor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safe_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d safe_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  safe-notification-service:
    build:
      context: ./email-tx-builder/packages/safe-notification-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3030
      - DATABASE_URL=postgresql://user:password@db:5432/safe_monitor
      - RELAYER_URL=https://safe-2fa-relayer.zk.email
      - CORS_ORIGIN=http://localhost:3000
      - FACTORY_ADDRESS=0x86227311CeDA2dbF64123854bcc359D6C4cDB8a3
      - RPC_URL=https://sepolia.infura.io/v3/${SWM_NEXT_PUBLIC_INFURA_TOKEN}
      - PRIVATE_KEY=${SNS_PRIVATE_KEY}
    volumes:
      - ./email-tx-builder/packages/safe-notification-service/src:/app/src
      - ./email-tx-builder/packages/safe-notification-service/prisma:/app/prisma
    networks:
      - safe_network
    ports:
      - 3030:3030

  safe-wallet:
    build:
      context: ./safe-wallet-monorepo
      args:
        - NEXT_PUBLIC_INFURA_TOKEN=${SWM_NEXT_PUBLIC_INFURA_TOKEN}
        - NEXT_PUBLIC_WC_PROJECT_ID=${SWM_NEXT_PUBLIC_WC_PROJECT_ID}
        - NEXT_PUBLIC_SNS_BACKEND_URL=http://localhost:3030
    depends_on:
      - safe-notification-service
    networks:
      - safe_network
    ports:
      - 3000:3000

volumes:
  postgres_data:

networks:
  safe_network:
    driver: bridge
